### ISSUE TITLE
[prod] MongoDB cluster

### ISSUE THREAD

**Issue by jakubgs** [dap-ps/infra-dapps#6]
Current dev setup uses just one host. For production we will need at least 3-host cluster for acceptable reliability. Affects #1.

**Comment by jakubgs** [comment]
According to this issue:
https://stackoverflow.com/questions/51149455/mongodb-getting-error-while-creating-new-user
Specifying the mechanisms when logging in to be `SCRAM-SHA-1` explicitly helps.

**Comment by jakubgs** [comment]
According to the [`README`](https://github.com/UnderGreen/ansible-role-mongodb) there's a suggested setting:
```yaml
# Configure setParameter option.
mongodb_set_parameters:
  {
    "enableLocalhostAuthBypass": "true",
    "authenticationMechanisms": "SCRAM-SHA-1,MONGODB-CR",
  }
```
Now, the question is, what is a MongoDB `setParameter`.

**Comment by jakubgs** [comment]
This is used in the MongoDB configuration template:
```jinja2
{% if mongodb_set_parameters -%}
setParameter:
  {% for key, value in mongodb_set_parameters.items() -%}
  {{ key }}: {{ value }}
  {% endfor -%}
{% endif %}
```
https://github.com/UnderGreen/ansible-role-mongodb/blob/196c796ef9339c267f8fd0a96c91c5bec20015c3/templates/mongod.conf.j2#L81-L86
Here are the MongoDB docs for this config section:
https://docs.mongodb.com/manual/reference/parameters/

**Comment by jakubgs** [comment]
Apparently:

>`authenticationMechanisms`
>Specifies the list of authentication mechanisms the server accepts.

https://docs.mongodb.com/manual/reference/parameters/#param.authenticationMechanisms

**Comment by jakubgs** [comment]
The task that fails is this one:
```yaml
- name: create administrative user siteUserAdmin
  mongodb_user:
    database: admin
    name: "{{ item.name }}"
    password: "{{ item.password }}"
    update_password: "{{ mongodb_user_update_password }}"
    roles: "{{ item.roles }}"
    login_port: "{{ mongodb_net_port }}"
  with_items:
    - {
      name: "{{ mongodb_user_admin_name }}",
      password: "{{ mongodb_user_admin_password }}",
      roles: "userAdminAnyDatabase"
      }
  no_log: true
```
https://github.com/UnderGreen/ansible-role-mongodb/blob/196c796ef9339c267f8fd0a96c91c5bec20015c3/tasks/auth_initialization.yml#L16-L30

What's interesting is that it only specifies the `login_port`, but not `login_user` or `login_password`:
https://docs.ansible.com/ansible/latest/modules/mongodb_user_module.html
